// Generated by CoffeeScript 1.12.7
(function() {
  var boxes, danger_zone_cnt, field, generate_danger_zone, get_boxes, logs, person;

  person = prompt("Please enter your name.");

  field = document.getElementById("field");

  logs = document.getElementById("logs");

  boxes = document.getElementsByClassName("box");

  danger_zone_cnt = 1;

  generate_danger_zone = function() {
    var danger_zone, j, random_size, results, x_loc, y_loc;
    results = [];
    for (j = 1; j <= 10; j++) {
      random_size = Math.floor(Math.random() * 30) + 20;
      y_loc = Math.floor(Math.random() * 525) + 50;
      x_loc = Math.floor(Math.random() * 950);
      danger_zone = document.createElement("P");
      danger_zone.className = "box";
      danger_zone.id = danger_zone_cnt;
      danger_zone.setAttribute("style", ("width: " + random_size + "px;") + ("height: " + random_size + "px;") + ("left: " + x_loc + "px;") + ("top: " + y_loc + "px;"));
      field.appendChild(danger_zone);
      results.push(danger_zone_cnt++);
    }
    return results;
  };

  generate_danger_zone();

  document.getElementById("field").addEventListener("click", function() {
    var log;
    log = document.createElement("P");
    log.textContent = "You clicked a safe zone! X: " + event.clientX + "Y: " + event.clientY + ".";
    logs.appendChild(log);
  });

  get_boxes = function() {
    var i, j, ref;
    for (i = j = 0, ref = boxes.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      boxes[i].addEventListener("click", function() {
        event.stopPropagation();
        alert("Aww sorry, " + person + "! You detonated a bomb.");
        field.innerHTML = "";
        logs.innerHTML = "";
        generate_danger_zone();
        boxes = document.getElementsByClassName("box");
        console.log(boxes);
        get_boxes();
      });
    }
  };

  get_boxes();

}).call(this);
